/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CeoOfDangDreamPropertyRouteImport } from './routes/ceo-of-dang-dream-property'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoOfDangDreamPropertyRoute = CeoOfDangDreamPropertyRouteImport.update({
  id: '/ceo-of-dang-dream-property',
  path: '/ceo-of-dang-dream-property',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ceo-of-dang-dream-property': typeof CeoOfDangDreamPropertyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/properties': typeof PropertiesRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ceo-of-dang-dream-property': typeof CeoOfDangDreamPropertyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/properties': typeof PropertiesRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ceo-of-dang-dream-property': typeof CeoOfDangDreamPropertyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/properties': typeof PropertiesRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ceo-of-dang-dream-property'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/list-property'
    | '/login'
    | '/news'
    | '/properties'
    | '/services'
    | '/signup'
    | '/tools'
    | '/update-password'
    | '/auth/callback'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ceo-of-dang-dream-property'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/list-property'
    | '/login'
    | '/news'
    | '/properties'
    | '/services'
    | '/signup'
    | '/tools'
    | '/update-password'
    | '/auth/callback'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ceo-of-dang-dream-property'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/list-property'
    | '/login'
    | '/news'
    | '/properties'
    | '/services'
    | '/signup'
    | '/tools'
    | '/update-password'
    | '/auth/callback'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CeoOfDangDreamPropertyRoute: typeof CeoOfDangDreamPropertyRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ListPropertyRoute: typeof ListPropertyRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  PropertiesRoute: typeof PropertiesRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  ToolsRoute: typeof ToolsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo-of-dang-dream-property': {
      id: '/ceo-of-dang-dream-property'
      path: '/ceo-of-dang-dream-property'
      fullPath: '/ceo-of-dang-dream-property'
      preLoaderRoute: typeof CeoOfDangDreamPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CeoOfDangDreamPropertyRoute: CeoOfDangDreamPropertyRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ListPropertyRoute: ListPropertyRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  PropertiesRoute: PropertiesRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  ToolsRoute: ToolsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
